import { FileJson, FileText, Download } from 'lucide-react'

function formatReport(incident, logs, analysis) {
  return {
    report: {
      generated_at: new Date().toISOString(),
      platform: 'Sentinel AI',
    },
    incident,
    logs,
    ai_analysis: analysis || null,
  }
}

function downloadJSON(incident, logs, analysis) {
  const data = formatReport(incident, logs, analysis)
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `sentinel-ai-${incident.id}-report.json`
  a.click()
  URL.revokeObjectURL(url)
}

function downloadText(incident, logs, analysis) {
  const lines = [
    '═══════════════════════════════════════════════════',
    '           SENTINEL AI — INCIDENT REPORT           ',
    '═══════════════════════════════════════════════════',
    '',
    `Incident ID  : ${incident.id}`,
    `Title        : ${incident.title}`,
    `Severity     : ${incident.severity.toUpperCase()}`,
    `Status       : ${incident.status.toUpperCase()}`,
    `Source       : ${incident.source}`,
    `Timestamp    : ${incident.timestamp}`,
    `Systems      : ${incident.affected_systems?.join(', ')}`,
    '',
    '─── DESCRIPTION ────────────────────────────────────',
    incident.description,
    '',
  ]

  if (analysis) {
    lines.push('─── AI SUMMARY ─────────────────────────────────────')
    lines.push(analysis.summary || '')
    lines.push('')
    lines.push('─── ROOT CAUSE ─────────────────────────────────────')
    lines.push(analysis.root_cause || '')
    lines.push(`Confidence: ${Math.round((analysis.confidence || 0) * 100)}%`)
    lines.push('')
    lines.push('─── BUSINESS IMPACT ────────────────────────────────')
    lines.push(analysis.business_impact || '')
    lines.push('')

    if (analysis.timeline?.length) {
      lines.push('─── TIMELINE ───────────────────────────────────────')
      analysis.timeline.forEach((e, i) => lines.push(`  ${i + 1}. ${e}`))
      lines.push('')
    }

    if (analysis.recommendations?.length) {
      lines.push('─── RECOMMENDATIONS ────────────────────────────────')
      analysis.recommendations.forEach((r, i) => {
        lines.push(`  ${i + 1}. [${r.priority?.toUpperCase()}] ${r.action}`)
      })
      lines.push('')
    }
  }

  if (logs?.length) {
    lines.push('─── EVENT LOGS ─────────────────────────────────────')
    logs.forEach(log => lines.push(`  [${log.level}] ${log.message}`))
    lines.push('')
  }

  lines.push('─── END OF REPORT ──────────────────────────────────')
  lines.push(`Generated by Sentinel AI on ${new Date().toLocaleString()}`)

  const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `sentinel-ai-${incident.id}-report.txt`
  a.click()
  URL.revokeObjectURL(url)
}

export default function ExportReport({ incident, logs, analysis }) {
  if (!incident) return null

  return (
    <div className="flex gap-2">
      <button
        onClick={() => downloadText(incident, logs, analysis)}
        className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs bg-gray-700 hover:bg-gray-600 text-gray-300 transition-colors"
        title="Download text report"
      >
        <FileText size={13} /> Export TXT
      </button>
      <button
        onClick={() => downloadJSON(incident, logs, analysis)}
        className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs bg-gray-700 hover:bg-gray-600 text-gray-300 transition-colors"
        title="Download JSON report"
      >
        <FileJson size={13} /> Export JSON
      </button>
    </div>
  )
}
